RedditClone/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:new, :create]

  resource :session, only: [:new, :create, :destroy]

  resources :subs, except: [:destroy] do
    resources :posts, only: [:new]
  end

  resources :posts, except: [:new, :index]
end

RedditClone/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

RedditClone/app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :bigint(8)        not null, primary key
#  title      :string           not null
#  url        :string
#  content    :text
#  sub_id     :integer          not null
#  author_id  :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Post < ApplicationRecord
  validates :title, presence: true

  belongs_to :author,
             foreign_key: :author_id,
             class_name: :User

  belongs_to :sub,
             foreign_key: :sub_id,
             class_name: :Sub
end

RedditClone/app/models/sub.rb
# == Schema Information
#
# Table name: subs
#
#  id           :bigint(8)        not null, primary key
#  title        :string           not null
#  description  :text
#  moderator_id :integer          not null
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Sub < ApplicationRecord
  validates :title, :description, presence: true
  validates :title, uniqueness: true

  belongs_to :moderator,
             foreign_key: :moderator_id,
             class_name: :User

  has_many :posts,
           foreign_key: :sub_id,
           class_name: :Post
end

RedditClone/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint(8)        not null, primary key
#  username        :string           not null
#  session_token   :string           not null
#  password_digest :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ApplicationRecord
  validates :password, length: { minimum: 6, allow_nil: true }
  validates :username, :password_digest, :session_token, presence: true
  validates :session_token, :username, uniqueness: true

  attr_reader :password

  after_initialize :ensure_session_token

  has_many :subs,
           foreign_key: :moderator_id,
           class_name: :Sub

  has_many :posts,
           foreign_key: :author_id,
           class_name: :Post

  #FGRIPE

  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)
    user && user.is_password?(password) ? user : nil
  end

  def self.generate_session_token
    SecureRandom::urlsafe_base64
  end

  def reset_session_token!
    self.session_token = User.generate_session_token
    self.save!
    self.session_token
  end

  def ensure_session_token
    self.session_token ||= User.generate_session_token
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def password=(password)
    self.password_digest = BCrypt::Password.create(password)
    @password = password
  end
end

RedditClone/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?

  def login(user)
    session[:session_token] = user.reset_session_token!
    @current_user = user
  end

  def logout
    current_user.reset_session_token!
    session[:session_token] = nil
  end

  def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def logged_in?
    !!current_user
  end

  def ensure_logged_in
    redirect_to new_session_url unless logged_in?
  end

end

RedditClone/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :ensure_ownership, only: [:edit, :update]

  def new
    @sub_id = params[:id]
    @post = Post.new
  end

  def show
    @post = Post.find(params[:id])
  end

  def create
    @post = current_user.posts.new(post_params)
    @post.sub_id = params[:sub_id]
    if @post.save
      redirect_to post_url(@post)
    else
      flash.now[:errors] = @post.errors.full_messages
      @sub_id = params[:sub_id]
      render :new
    end
  end

  def edit
    @sub_id = params[:id]
    # @post = Post.find(params[:id])
  end

  def update
    @post.author_id = current_user.id
    @post.sub_id = params[:sub_id]
    if @post.update(post_params)
      redirect_to post_url(@post)
    else
      flash.now[:errors] = @post.errors.full_messages
      @sub_id = params[:sub_id]
      render :edit
    end
  end

  def destroy
    @post = current_user.posts.find(params[:id])
    @post.destroy
    redirect_to subs_url
  end

  private

  def ensure_ownership
    @post = current_user.posts.find(params[:id])
    redirect_to post_url(params[:id]) unless @post
  end

  def post_params
    params.require(:post).permit(:title, :url, :content)
  end
end

RedditClone/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    render :new
  end

  def create
    @user = User.find_by_credentials(
      params[:user][:username],
      params[:user][:password]
    )
    if @user
      login(@user)
      redirect_to subs_url
    else
      flash.now[:errors] = ["Invalid username/password"]
      render :new
    end
  end

  def destroy
    logout
    redirect_to new_session_url
  end
end

RedditClone/app/controllers/subs_controller.rb
class SubsController < ApplicationController
  before_action :ensure_ownership, only: [:edit, :update]

  def index
    @subs = Sub.all
    render :index
  end

  def new
    @sub = Sub.new
    render :new
  end

  def create
    @sub = current_user.subs.new(sub_params) #creating a new sub which automatically belongs to this user through an association. 
    if @sub.save
      redirect_to subs_url
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :new
    end
  end

  def show
    @sub = Sub.find(params[:id])
  end

  def edit
    @sub ||= current_user.subs.find(params[:id])
  end

  def update
    @sub ||= current_user.subs.find(params[:id])
    if (@sub && @sub.update(sub_params))
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :edit
    end
  end

  private
  
  def ensure_ownership
    @sub = current_user.subs.find(params[:id])
    redirect_to sub_url(params[:id]) unless @sub
  end

  def sub_params
    params.require(:sub).permit(:title, :description)
  end
end

RedditClone/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login(@user)
      redirect_to subs_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

RedditClone/app/helpers/application_helper.rb
module ApplicationHelper
end

RedditClone/app/helpers/posts_helper.rb
module PostsHelper
end

RedditClone/app/helpers/sessions_helper.rb
module SessionsHelper
end

RedditClone/app/helpers/subs_helper.rb
module SubsHelper
end

RedditClone/app/helpers/users_helper.rb
module UsersHelper
end

RedditClone/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RedditClone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <form action="<%= session_url  %>" method="POST">
     <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
     <input type="hidden" name="_method" value="DELETE">
     <input type="submit" value="Logout">
    </form>
    <%= yield %>
  </body>
</html>

RedditClone/app/views/posts/edit.html.erb
Edit Post

<form action="<%= post_url(@post)  %>" method="POST">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <input type="hidden" name="_method" value="PATCH">
    <input type="hidden" name="sub_id" value=" <%= @sub_id %> "> 
    <label> Title
        <input type="text" name="post[title]"  value="<%= @post.title  %>">
    </label>
    <label> URL
        <input type="text" name="post[url]"  value="<%= @post.url  %>">
    </label>
    <label> Content
        <input type="text" name="post[content]"  value="<%=  @post.content %>">
    </label>
  
    <input type="submit" value="Save Post">
</form>

RedditClone/app/views/posts/new.html.erb
New Post

<form action="<%= posts_url  %>" method="POST">
<% debugger %>
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="hidden" name="sub_id" value=" <%= @sub_id %> "> 
  <label> Title
       <input type="text" name="post[title]"  value="<%= @post.title  %>">
  </label>
  <label> URL
       <input type="text" name="post[url]"  value="<%= @post.url  %>">
  </label>
  <label> Content
       <input type="text" name="post[content]"  value="<%=  @post.content %>">
  </label>
  
  <input type="submit" value="Save Post">
</form>

RedditClone/app/views/posts/show.html.erb
<a href="<%= sub_url(@post.sub) %>">Back to Sub</a>


Post

Sub: <%= @post.sub.title %>
Author: <%= @post.author.username %>

Title: <%= @post.title %>
URL: <%= @post.url %>
Content: <%= @post.content %>

<a href="<%= edit_post_url(@post) %>">Edit</a>

<form action="<%= post_url(@post)  %>" method="POST">
 <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
 <input type="hidden" name="_method" value="DELETE">
 <input type="submit" value="Delete">
</form>

RedditClone/app/views/subs/edit.html.erb
Edit Sub
<form action="<%= sub_url(@sub)  %>" method="POST">
 <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
 <input type="hidden" name="_method" value="PATCH">
 <label> Title
      <input type="text" name="sub[title]"  value="<%= @sub.title  %>">
 </label>
 <label> Description
      <input type="text" name="sub[description]"  value="<%= @sub.description %>">
 </label>
 <input type="submit" value="Save">
</form>

RedditClone/app/views/subs/index.html.erb
All Subs:

<br>
<br>
<% @subs.each do |sub| %>
<a href="<%= sub_url(sub) %>"><%= sub.title %></a>
<br>
  Moderator: <%= sub.moderator.username %>
  <br>
  Description: <%= sub.description %>
  <br>
  <br>
<% end %>
<br>
<a href="<%= new_sub_url %>">Create A New Sub</a>

RedditClone/app/views/subs/new.html.erb
New Sub
<form action="<%= subs_url  %>" method="POST">
 <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
 <label> Title
      <input type="text" name="sub[title]"  value="<%= @sub.title  %>">
 </label>
 <label> Description
      <input type="text" name="sub[description]"  value="<%= @sub.description %>">
 </label>
 <input type="submit" value="Save">
</form>

RedditClone/app/views/subs/show.html.erb
<a href="<%= subs_url %>">Back to All Subs</a>
<h1><%= @sub.title %></h1>
<%= @sub.moderator.username %>
<%= @sub.description %>
POSTS
<% @sub.posts.each do |post| %>
<a href="<%= post_url(post) %>">
  <%= post.title %>
  <%= post.author.username %>
  <%= post.url %>
</a>
<% end %>

<a href="<%= new_sub_post_url(@sub) %>">Add A Post</a>
  

RedditClone/app/views/users/new.html.erb
Sign Up

<form action="<%= users_url %>" method="POST">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <label> Username
       <input type="text" name="user[username]"  value="<%= @user.username  %>">
  </label>
  <label> Password
       <input type="password" name="user[password]">
  </label>
  
  <input type="submit" value="Sign up!">
  
</form> 